
# This file has been generated at Fri Aug 27 18:48:17 2010

from openalea.core import *


__name__ = 'openalea.stocatree'

__editable__ = True
__description__ = 'stocatree.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr/doc/openalea/pylab/doc/_build/html/contents.html'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Thomas Cokelaer'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'icon.png'


__all__ = ['test']


test = CompositeNodeFactory(name='test',
                            description='',
                            category='Unclassified',
                            doc='',
                            inputs=[],
                            outputs=[],
                            elt_factory={2: ('openalea.misc', 'SharedDataBrowser'),
                                         3: ('openalea.data structure.string', 'string'),
                                         4: ('openalea.data structure.string', 'string'),
                                         5: ('lpymtg.macro', 'RunLpy'),
                                         6: ('vplants.l-py', 'plot')},
                            elt_connections={165768668: (5, 0, 6, 0),
                                             165768680: (5, 1, 6, 1),
                                             165768692: (2, 0, 5, 0),
                                             165768704: (3, 0, 2, 2),
                                             165768716: (4, 0, 2, 0)},
                            elt_data={2: {'block': False,
                                          'caption': 'SharedDataBrowser',
                                          'delay': 0,
                                          'factory': '<openalea.core.node.NodeFactory object at 0xb90c5ac> : "SharedDataBrowser"',
                                          'hide': True,
                                          'id': 2,
                                          'lazy': True,
                                          'port_hide_changed': set(),
                                          'posx': -373.83739837398372,
                                          'posy': -385.29268292682929,
                                          'priority': 0,
                                          'use_user_color': False,
                                          'user_application': None,
                                          'user_color': None},
                                      3: {'block': False,
                                          'caption': "'stocatree.lpy'",
                                          'delay': 0,
                                          'factory': '<openalea.core.node.NodeFactory object at 0xb453a0c> : "string"',
                                          'hide': True,
                                          'id': 3,
                                          'lazy': True,
                                          'port_hide_changed': set(),
                                          'posx': -207.0,
                                          'posy': -472.0,
                                          'priority': 0,
                                          'use_user_color': False,
                                          'user_application': None,
                                          'user_color': None},
                                      4: {'block': False,
                                          'caption': "'stocatree'",
                                          'delay': 0,
                                          'factory': '<openalea.core.node.NodeFactory object at 0xb453a0c> : "string"',
                                          'hide': True,
                                          'id': 4,
                                          'lazy': True,
                                          'port_hide_changed': set(),
                                          'posx': -330.0,
                                          'posy': -471.0,
                                          'priority': 0,
                                          'use_user_color': False,
                                          'user_application': None,
                                          'user_color': None},
                                      5: {'block': False,
                                          'caption': 'RunLpy',
                                          'delay': 0,
                                          'factory': '<openalea.core.compositenode.CompositeNodeFactory object at 0xb04a74c> : "RunLpy"',
                                          'hide': True,
                                          'id': 5,
                                          'lazy': True,
                                          'port_hide_changed': set(),
                                          'posx': -302.03252032520328,
                                          'posy': -327.96747967479678,
                                          'priority': 0,
                                          'use_user_color': False,
                                          'user_application': None,
                                          'user_color': None},
                                      6: {'block': False,
                                          'caption': 'plot',
                                          'delay': 0,
                                          'factory': '<openalea.core.node.NodeFactory object at 0xb91878c> : "plot"',
                                          'hide': True,
                                          'id': 6,
                                          'lazy': True,
                                          'port_hide_changed': set(),
                                          'posx': -287.71544715447158,
                                          'posy': -275.82926829268297,
                                          'priority': 0,
                                          'use_user_color': False,
                                          'user_application': None,
                                          'user_color': None},
                                      '__in__': {'block': False,
                                                 'caption': 'In',
                                                 'delay': 0,
                                                 'hide': True,
                                                 'id': 0,
                                                 'lazy': True,
                                                 'port_hide_changed': set(),
                                                 'posx': 0,
                                                 'posy': 0,
                                                 'priority': 0,
                                                 'use_user_color': True,
                                                 'user_application': None,
                                                 'user_color': None},
                                      '__out__': {'block': False,
                                                  'caption': 'Out',
                                                  'delay': 0,
                                                  'hide': True,
                                                  'id': 1,
                                                  'lazy': True,
                                                  'port_hide_changed': set(),
                                                  'posx': 0,
                                                  'posy': 0,
                                                  'priority': 0,
                                                  'use_user_color': True,
                                                  'user_application': None,
                                                  'user_color': None}},
                            elt_value={2: [(1, "'*'")],
                                       3: [(0, "'stocatree.lpy'")],
                                       4: [(0, "'stocatree'")],
                                       5: [(1, "''"), (2, '4000'), (3, '{}')],
                                       6: [],
                                       '__in__': [],
                                       '__out__': []},
                            elt_ad_hoc={2: {'position': [-373.83739837398372, -385.29268292682929], 'userColor': None, 'useUserColor': False},
                                        3: {'position': [-207.0, -472.0], 'userColor': None, 'useUserColor': False},
                                        4: {'position': [-330.0, -471.0], 'userColor': None, 'useUserColor': False},
                                        5: {'position': [-302.03252032520328, -327.96747967479678], 'userColor': None, 'useUserColor': False},
                                        6: {'position': [-287.71544715447158, -275.82926829268297], 'userColor': None, 'useUserColor': False},
                                        '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
                                        '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                            lazy=True,
                            eval_algo='LambdaEvaluation',
                            )

